name: Test

on:
  push:
    branches: ["main"]
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          cache: true

      - name: Install dependencies
        run: go mod tidy

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x

      - name: Test
        run: task test
